### ISSUE TITLE
关于H与Memory的差异性讨论

### ISSUE THREAD

**Issue by jayeew** [haiyun202/MMP#1]
我注意到论文中比较直觉的让H和C保持差异性，前者用于预测，后者用于传播，但深层的考虑好像没太解释清楚。
在代码中，超参lambda用来保证第二项损失，即保证H与C事实上的差异性，但只有cornell、wisconsin两个数据集是1，其他数据集都是0、0.1、0.2等很接近0的数，
换句话说，大部分情况下并没有从事实上保证H与C的差异。

既然不保证二者的差异性，如果我们为了简化而去掉模型每层的卷积参数W1和映射参数W2，去掉alphas，模型大致可以等价于H+AH+A^2H+ ... ...的常见形式，
但这似乎又失去了模型特色——“让H和C保持差异性，前者用于预测，后者用于传播”。

希望作者能解释一下，不胜感激。

**Comment by JC-202** [comment]
您好，非常感谢对我们工作的关注，H和C的差异性的主要目的是提升模型的鲁棒性和泛化性。
1）这里H与C的独立性约束可以看作一个先验，因此其对于不同的数据集而言程度是不同的，如当邻居信息对分类没有什么帮助的时候可以适当提升独立性约束的程度，当领域信息对当前节点的分类有帮助时可适当调低。
2）MMP确实在特定情况下可以退化为简化版模型，即图上的多项式滤波器形式，这也保证了其表达能力的底线，实际中会对数据集自适应的进行学习。
